const LINKS = {
    home: "/",
    overview: "/#overview",
    mission: "/#mission",
    metaprotocols: "/metaprotocols",
    tools: "/tools",
    donate: "/donate",
    documentation:
        "https://layer1.gitbook.io/layer1-foundation/protocols/brc-20/documentation",
    bestinslot: "https://bestinslot.xyz/",
    domo: "https://www.domo.com/",
    okx: "https://www.okx.com/",
    ordinalswallet: "https://ordinalswallet.com/",
    oyl: "https://www.oyl.io/",
    gitbook: "https://layer1.gitbook.io/layer1-foundation/foundation/purpose",
    forum: "https://l1f.discourse.group/latest",
    partners: "/#partners",
    bitcoinwhitepaper: "https://domo-2.gitbook.io/brc-20-experiment/",
    twitter: "https://twitter.com/L1Fxyz",
    opi: "https://opi.network/",
    metashrew: "https://www.sandshrew.io/",
    ordinalsbot: "https://ordinalsbot.com/",
    ordio: "https://www.ord.io/",
    ordiscan: "https://ordiscan.com/",
    email: "mailto:",
    governance: "/#governance",
    strapi: "https://cms.l1f.xyz",
};

export default LINKS;
