import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col items-center">
          <div className="max-w-7xl">        
            <Header />
            <main className="py-3 px-4 md:py-4 md:px-10">{children}</main>
            <Footer />
          </div>
        </div>
      </body>
      <body className="px-16 py-8">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
